# Git diff
[[mgr.prepend_keymap]]
on   = [ "i", "c" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

# jump-to-char
[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

# mount
[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

# smart enter
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
